server:
  port: 7002
eureka:
  instance:
    hostname: eureka7002.com
  client:
    #是否将自己的路径注册到eureka上。eureka server是服务端因此不需要，eureka client客户端（提供者）需要，默认值是true
    register-with-eureka: false
    #是否现需要从eureka中抓取路径。eureka server是服务端因此不需要，eureka client客户端（消费者）需要，默认值是true
    fetch-registry: false
    service-url:
      #eureka服务端地址，将来客户端使用该地址和eureka进行通信，默认也是这个值
      defaultZone: http://eureka7001.com:7001/eureka
      spring:
        application:
          name: eureka-server-7002